services:    
  nginx:
    labels:
      caddy: stage.ildeposito.org
      caddy.reverse_proxy: "{{upstreams 80}}"   
      caddy.basicauth: "*"
      caddy.basicauth.ildeposito: "$2b$14$nNWWEXBKad18l1Vs5VaRRuqOcN3dhWY9AVIQTTriF6nrdPeCGfvFy"   