services:
  mariadb:
    image: wodby/mariadb:$MARIADB_TAG
    stop_grace_period: 30s
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_TRANSACTION_ISOLATION: READ-COMMITTED
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mariadb-init:/docker-entrypoint-initdb.d
    networks:
      - backend-internal

  php:
    image: wodby/drupal-php:$PHP_TAG
    restart: unless-stopped
    environment:
      PHP_EXTENSIONS_DISABLE: xhprof,spx
      PHP_MAIL_MIXED_LF_AND_CRLF: On
      PHP_APCU_SHM_SIZE: 64M
      PHP_SESSION_COOKIE_SAMESITE: Strict
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_HOST: $DB_HOST
      DRUPAL_HASH_SALT: ${DRUPAL_HASH_SALT:-}
      GITHUB_APP_ID: ${GITHUB_APP_ID:-}
      GITHUB_APP_INSTALLATION_ID: ${GITHUB_APP_INSTALLATION_ID:-}
      SMTP_HOST: ${SMTP_HOST:-}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_USER: ${SMTP_USER:-}
      SMTP_PASS: ${SMTP_PASS:-}
      MAIL_FROM: ${MAIL_FROM:-}
      PHP_FPM_CLEAR_ENV: "no"
    volumes:
    - ./:/var/www/html:cached
    - ../backup:/var/backup_migrate
    networks:
      - backend-internal

  crond:
    init: true
    image: wodby/drupal-php:$PHP_TAG
    restart: unless-stopped
    environment:
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_HOST: $DB_HOST
      CRONTAB: "0 * * * * drush -r /var/www/html/web cron"
    command: sudo -E crond -f -d 0
    volumes:
      - ./:/var/www/html:cached
    networks:
      - backend-internal

  nginx:
    image: wodby/nginx:$NGINX_TAG
    restart: unless-stopped
    depends_on:
      - php
    environment:
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
      NGINX_VHOST_PRESET: $NGINX_VHOST_PRESET
    volumes:
    - ./:/var/www/html:cached
    networks:
      backend-internal:
      caddy:
      app-internal:
        aliases:
          - drupal-api

volumes:
  mariadb_data:

networks:
  backend-internal:
    driver: bridge
  caddy:
    external: true
  app-internal:
    name: ildeposito-${ENV}-internal
    external: true