services:
  mariadb:
    container_name: ildeposito_prod_backend_mariadb

  php:
    container_name: ildeposito_prod_backend_php
    environment:
      ILDEPOSITO_ENV: prod
      FILES_DIR_PERMISSIONS_FIX: 0
      DRUPAL_SITE_DIR_PERMISSIONS_FIX: 0

  crond:
    container_name: ildeposito_prod_backend_crond

  nginx:
    container_name: ildeposito_prod_backend_nginx
    labels:
      caddy: admin.ildeposito.org
      caddy.basicauth: "/*"
      caddy.basicauth.ildeposito: "${BASIC_AUTH_HASH}"
      caddy.reverse_proxy: "{{upstreams 80}}"
