services:
  mariadb:
    container_name: ildeposito_stage_backend_mariadb

  php:
    container_name: ildeposito_stage_backend_php
    environment:
      ILDEPOSITO_ENV: stage
      FILES_DIR_PERMISSIONS_FIX: 0
      DRUPAL_SITE_DIR_PERMISSIONS_FIX: 0

  crond:
    container_name: ildeposito_stage_backend_crond

  nginx:
    container_name: ildeposito_stage_backend_nginx
    labels:
      caddy: admin-stage.ildeposito.org
      caddy.basicauth: "/*"
      caddy.basicauth.ildeposito: "${BASIC_AUTH_HASH}"
      caddy.@jsonapi.path: /jsonapi/*
      caddy.respond: "@jsonapi 403"
      caddy.reverse_proxy: "{{upstreams 80}}"
