services:    
  mariadb:
    container_name: ildeposito_stage_mariadb

  php:
    container_name: ildeposito_stage_php
    environment:
      ILDEPOSITO_ENV: "stage"

  crond:
    container_name: ildeposito_stage_crond
  
  memcached:
    container_name: ildeposito_stage_memcached
  
  solr:
    container_name: ildeposito_stage_solr
  
  zookeeper:
    container_name: ildeposito_stage_zookeeper

  nginx:
    container_name: ildeposito_stage_nginx
    labels:
      caddy: stage.ildeposito.org
      caddy.basic_auth: "*"
      caddy.basic_auth.ildeposito: "$$2b$$12$$lkOTABkIjzM7G3w.uUZjD.122R3LG5lI3DMB11Occ2TR/XSNI1U4y"
      caddy.reverse_proxy: "{{upstreams 80}}"  
   