services:
  mariadb:
    image: wodby/mariadb:$MARIADB_TAG
    stop_grace_period: 30s
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_TRANSACTION_ISOLATION: READ-COMMITTED
    volumes:
      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
    networks:
      - internal  

  php:
    image: wodby/drupal-php:$PHP_TAG
    restart: unless-stopped
    environment:
      PHP_EXTENSIONS_DISABLE: xhprof,spx
      PHP_MAIL_MIXED_LF_AND_CRLF: On
      PHP_APCU_SHM_SIZE: 64M
      PHP_SESSION_COOKIE_SAMESITE: Strict
    volumes:
    - ./:/var/www/html:cached
    - ../backup:/var/backup_migrate  
    networks:
      - internal      

  crond:
    init: true
    image: wodby/drupal-php:$PHP_TAG
    restart: unless-stopped
    environment:
      CRONTAB: "0 * * * * drush -r /var/www/html/web cron"
    command: sudo -E crond -f -d 0
    volumes:
    - ./:/var/www/html:cached
    networks:
      - internal      

  nginx:
    image: wodby/nginx:$NGINX_TAG
    restart: unless-stopped
    depends_on:
    - php
    environment:
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
      NGINX_VHOST_PRESET: $NGINX_VHOST_PRESET
    labels:
      caddy: stage.ildeposito.org
      caddy.reverse_proxy: "{{upstreams 80}}"   
    volumes:
    - ./:/var/www/html:cached
    networks:
      - internal  
      - caddy    

  memcached:
    restart: unless-stopped
    image: wodby/memcached:$MEMCACHED_TAG
    networks:
      - internal  

  solr:
    image: wodby/solr:$SOLR_TAG
    restart: unless-stopped
    environment:
      SOLR_OPTS: "-Dsolr.config.lib.enabled=true"
      SOLR_MODULES: extraction,langid,ltr,analysis-extras
      ZK_HOST: zookeeper:2181
      SOLR_HEAP: 1024m
    depends_on:
    - zookeeper
    networks:
      - internal

  zookeeper:
    image: wodby/zookeeper:$ZOOKEEPER_TAG
    restart: unless-stopped
    networks:
      - internal 

networks:
  internal:
    driver: bridge
  caddy:
    external: true