keep_admin_menu: 0
settings:
  -
    menu: staff
    role:
      staff: staff
      god: god
      anonymous: '0'
      authenticated: '0'
      administrator: '0'
      api: '0'
    excluded_role:
      anonymous: '0'
      authenticated: '0'
      administrator: '0'
      staff: '0'
      api: '0'
      god: '0'
    icons:
      'menu_link_content:256fb95e-623f-4a2c-aa99-cbaf9e814344': structure-view
    admin_menu: use_global
    actions:
      remove_setting: 'Remove rule'
