_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: it
uuid: 541fc72c-bd22-44ca-a91e-f8f697223f94
name: ilDeposito10
mail: sergio.durzu@gmail.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: it
mail_notification: ''
