jobs:
  deploy:
    runs-on: [self-hosted, ildeposito]
    defaults:
      run:
        working-directory: /home/ubuntu/sergej/websites/ildeposito_stage/code_stage

    steps:
      - name: Pull latest code
        run: git pull origin main

      - name: Install dependencies
        run: composer install --ignore-platform-reqs

      - name: Run database updates
        run: drush stage updb -y

      - name: Import configuration
        run: drush stage cim -y

      - name: Clear cache
        run: drush stage cr